---
kind: pipeline
name: Apply templates

steps:

- name: Terraform apply
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
    BIGIP_PASS:
      from_secret: bigip_pass
    VAULT_ADDR:
      from_secret: vault_addr
    TF_VAR_gke_username:
      from_secret: gke_username
    TF_VAR_gke_password:
      from_secret: gke_password
  commands:
  - cd terraform-ansible-google/non-prod/
  #- terragrunt apply-all --terragrunt-non-interactive -auto-approve
  - terragrunt destroy-all --terragrunt-non-interactive -force

- name: SSH key preparation for Ansible Plugin
  image: tkam8/tfansible:latest
  environment:
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
  commands: 
  # Write the ssh key to disk
  - mkdir /drone/src/gcp
  - printenv GCE_SSH_KEY > /drone/src/gcp/gcp_ssh_key
  - chmod 400 /drone/src/gcp/gcp_ssh_key

- name: Apply Ansible playbook (asia)
  image: tkam8/tfansible:latest
  environment:
    BIGIP_PASS:
      from_secret: bigip_pass  
  commands: 
  - ls terraform-ansible-google/non-prod/asia-northeast1/stage/ansible/
  - cd terraform-ansible-google/non-prod/asia-northeast1/stage/ansible/playbooks/
  - ansible-playbook --inventory inventory/hosts -vvvv site.yml

- name: Slack notification
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook:
      from_secret: slack_webhook
    channel: sandbox
    template: >
      {{#success build.status}}
        Merge for build {{build.number}} succeeded. Here's a tequila~.
      {{else}}
        Build {{build.number}} failed. Fix me please.
      {{/success}}

trigger:
  branch:
  - master
  event:
  - push

